package: geolocation
version: '2.1.3'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/geolocation

page:
    title: translate:geolocation_title
    pjax: true
    icon: rex-icon fa-globe
    perm: geolocation[]
    subpages:
        config:
            title: translate:geolocation_config
            icon: fa fa-wrench
            perm: 'admin[]'
        mapset:
            title: translate:geolocation_mapset
            perm: 'geolocation[mapset]'
            icon: fa fa-map
            subPath: pages/yform.php
        layer:
            title: translate:geolocation_layer
            perm: 'geolocation[layer]'
            icon: fa fa-cloud-download
            subPath: pages/yform.php
        docs:
            title: translate:geolocation_manpage
            icon: fa fa-book
            subPath: help.php
        clear_cache:
            title: 'translate:geolocation_clear_cache'
            perm: 'geolocation[clearcache]'
            itemclass: pull-right
            linkclass: 'btn btn-delete'
            href:
                # Zur Info: Die konkreten Parameter setzt kontext-bezogen pages/index.php

yform:
    geolocation/mapset:
        table_name: rex_geolocation_mapset
    geolocation/layer:
        table_name: rex_geolocation_layer
    geolocation/service:
        table_name: rex_geolocation_service

conflicts:
    packages:
        yform_geo_osm: '<1.2.6'

requires:
    php:
        version: '^8'
        extensions: [curl]
    redaxo: '^5.14.0'
    packages:
        cronjob: '^2.8.0'
        yform: '^4.0.0'

installer_ignore:
    - .github
    - .gitignore
    - .gitattributes
default_config:
    socket_proxy: ''
