package: geolocation
version: '0.1.0'
author: Friends Of REDAXO, Christoph Böcker
supportpage: https://github.com/FriendsOfREDAXO/pdfout

page:
    title: translate:geolocation_title
    perm: admin
    pjax: true
    icon: rex-icon fa-globe
    subpages:
        config:
            title: translate:geolocation_config
            icon: fa fa-wrench
        maps:
            title: translate:geolocation_maps
            icon: fa fa-map
            subPath: pages/yform.php
            itemattr: {table_name: rex_geolocation_maps}
        tiles:
            title: translate:geolocation_tiles
            icon: fa fa-cloud-download
            subPath: pages/yform.php
            itemattr: {table_name: rex_geolocation_tiles}
        clear_cache:
            title: 'translate:geolocation_clear_cache'
            itemclass: 'pull-right'
            linkclass: 'btn btn-delete'
            href:
                page: geolocation/config
                func: clear_cache
default_config:
    ttl: 10080
    maxfiles: 1000

requires:
    php:
        version: '>=7.1'
    redaxo: '^5.10.0'
    packages:
        cronjob: '^2.7'
        yform: '^3.4'
