package: geolocation
version: '0.10.0'
author: Christoph Böcker
supportpage: https://github.com/christophboecker/geolocation

page:
    title: translate:geolocation_title
    pjax: true
    icon: rex-icon fa-globe
    subpages:
        config:
            title: translate:geolocation_config
            icon: fa fa-wrench
            perm: admin[]
        mapset:
            title: translate:geolocation_mapset
            perm: geolocation[mapset]
            icon: fa fa-map
            subPath: pages/yform.php
        layer:
            title: translate:geolocation_layer
            perm: geolocation[layer]
            icon: fa fa-cloud-download
            subPath: pages/yform.php
        docs:
            title: translate:geolocation_manpage
            icon: fa fa-book
            subPath: help.php
        dummy:
            title: 'translate:geolocation_clear_cache'
            perm: geolocation[clearcache]
            itemclass: 'pull-right'
            linkclass: 'btn btn-delete'
            href:
                page: geolocation/config
                rex-api-call: geolocation_clearcache

yform:
    geolocation/mapset:
        table_name: rex_geolocation_mapset
    geolocation/layer:
        table_name: rex_geolocation_layer

requires:
    php:
        version: '>=7.3, <9'
    redaxo: '^5.12.0'
    packages:
        cronjob: '^2.8'
        yform: '^3.4'
