package: geolocation
version: '2.1.3'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/geolocation

page:
    title: translate:geolocation_title
    pjax: true
    icon: rex-icon fa-globe
    perm: geolocation[]
    subpages:
        config:
            title: translate:geolocation_config
            icon: fa fa-wrench
            perm: 'admin[]'
        mapset:
            title: translate:geolocation_mapset
            perm: 'geolocation[mapset]'
            icon: fa fa-map
            subPath: pages/yform.php
        layer:
            title: translate:geolocation_layer
            perm: 'geolocation[layer]'
            icon: fa fa-cloud-download
            subPath: pages/yform.php
        manual: 
            title: translate:geolocation_manpage
            icon: fa fa-book
            subpages: 
                install:
                    title: translate:geolocation_manpage_install
                    icon: fa fa-book
                    perm: 'admin[]'
                    subpages:
                        install:
                            title: Installation
                            icon: fa fa-wrench
                            subpath:  help.php
                        settings:
                            title: Einstellungen
                            subpath:  help.php
                mapset:
                    title: translate:geolocation_manpage_mapset
                    icon: fa fa-book
                    perm: 'geolocation[mapset]'
                    subpath:  help.php
                layer:
                    title: translate:geolocation_manpage_layer
                    icon: fa fa-book
                    perm: 'geolocation[layer]'
                    subpath:  help.php
                proxy:
                    title: translate:geolocation_manpage_proxy
                    icon: fa fa-book
                    perm: 'admin[]'
                    subpath:  help.php
                developer:
                    title: translate:geolocation_manpage_developer
                    icon: fa fa-book
                    perm: 'admin[]'
                    subpages:
                        php:
                            title: translate:geolocation_manpage_devphp
                            linkclass: xxx
                            subpath:  help.php
                        js:
                            title: translate:geolocation_manpage_devjs
                            subpath:  help.php
                        tools:
                            title: translate:geolocation_manpage_devtools
                            subpath:  help.php
                        geojson:
                            title: translate:geolocation_manpage_devgeojson
                            subpath:  help.php
                        math:
                            title: translate:geolocation_manpage_devmath
                            subpath:  help.php
        clear_cache:
            title: 'translate:geolocation_clear_cache'
            perm: 'geolocation[clearcache]'
            itemclass: pull-right
            linkclass: 'btn btn-delete'
            href:
                # Zur Info: Die konkreten Parameter setzt kontext-bezogen pages/index.php

yform:
    geolocation/mapset:
        table_name: rex_geolocation_mapset
    geolocation/layer:
        table_name: rex_geolocation_layer
    geolocation/service:
        table_name: rex_geolocation_service

# Schema: Seitenname = dateiname im ./docs-Verzeichnis
manual:
    geolocation/manual/install/install: install.md
    geolocation/manual/install/settings: settings.md
    geolocation/manual/mapset: mapset.md
    geolocation/manual/layer: layer.md
    geolocation/manual/proxy: proxy_cache.md
    geolocation/manual/developer/php: devphp.md
    geolocation/manual/developer/js: devjs.md
    geolocation/manual/developer/tools: devtools.md
    geolocation/manual/developer/geojson: devgeojson.md
    geolocation/manual/developer/math: devmath.md

conflicts:
    packages:
        yform_geo_osm: '<1.2.6'

requires:
    php:
        version: '^8'
        extensions: [curl]
    redaxo: '^5.14.0'
    packages:
        cronjob: '^2.8.0'
        yform: '^4.0.0'

installer_ignore:
    - .github
    - .gitignore
    - .gitattributes
default_config:
    socket_proxy: ''
