package: geolocation
version: '2.3.1'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/geolocation

page:
    title: translate:geolocation_title
    pjax: true
    icon: rex-icon fa-globe
    perm: geolocation[]
    subpages:
        mapset:
            title: translate:geolocation_mapset
            perm: 'geolocation[mapset]'
            icon: fa fa-map
            subPath: pages/yform.php
        layer:
            title: translate:geolocation_layer
            perm: 'geolocation[layer]'
            icon: fa fa-cloud-download
            subPath: pages/yform.php
        config:
            title: translate:geolocation_config
            icon: fa fa-cog
            perm: 'admin[]'
        manual: 
            title: translate:geolocation_manpage
            icon: fa fa-book
            subpages: 
                mapset:
                    title: translate:geolocation_manpage_mapset
                    icon: fa fa-earth-europe
                    perm: 'geolocation[mapset]'
                    subpath:  pages/manual.php
                layer:
                    title: translate:geolocation_manpage_layer
                    icon: fa fa-map
                    perm: 'geolocation[layer]'
                    subpath:  pages/manual.php
                proxy_cache:
                    title: translate:geolocation_manpage_proxy
                    icon: fa fa-route
                    perm: 'admin[]'
                    subpath:  pages/manual.php
                developer:
                    title: translate:geolocation_manpage_developer
                    icon: fa fa-user-gear
                    perm: 'geolocation[developer]'
                    subpages:
                        devphp:
                            title: translate:geolocation_manpage_devphp
                            subpath:  pages/manual.php
                        devjs:
                            title: translate:geolocation_manpage_devjs
                            subpath:  pages/manual.php
                        devtools:
                            title: translate:geolocation_manpage_devtools
                            subpath:  pages/manual.php
                        devgeojson:
                            title: translate:geolocation_manpage_devgeojson
                            subpath:  pages/manual.php
                        devmath:
                            title: translate:geolocation_manpage_devmath
                            subpath:  pages/manual.php
                install:
                    title: translate:geolocation_manpage_install
                    icon: fa fa-wrench
                    perm: 'admin[]'
                    subpages:
                        install:
                            title: Installation
                            icon: fa fa-wrench
                            subpath:  pages/manual.php
                        settings:
                            title: Einstellungen
                            icon: fa fa-cog
                            subpath:  pages/manual.php
        clear_cache:
            title: 'translate:geolocation_clear_cache'
            perm: 'geolocation[clearcache]'
            itemClass: pull-right
            linkClass: 'btn btn-delete'
            href:
                # Zur Info: Die konkreten Parameter setzt kontext-bezogen pages/index.php

yform:
    geolocation/mapset:
        table_name: FriendsOfRedaxo\Geolocation\Mapset
    geolocation/layer:
        table_name: FriendsOfRedaxo\Geolocation\Layer
    geolocation/service:
        table_name: geolocation_service

conflicts:
    packages:
        yform_geo_osm: '<1.2.6'

requires:
    php:
        version: '^8'
        extensions: [curl]
    redaxo: '^5.14.0'
    packages:
        cronjob: '^2.8.0'
        yform: '^4.0.0'

installer_ignore:
    - .github
    - .gitignore
    - .gitattributes
default_config:
    socket_proxy: ''
