package: geolocation
version: '0.9.0'
author: Christoph Böcker
supportpage: https://github.com/christophboecker/geolocation

page:
    title: translate:geolocation_title
    perm: admin
    pjax: true
    icon: rex-icon fa-globe
    subpages:
        config:
            title: translate:geolocation_config
            icon: fa fa-wrench
            perm: admin[]
        mapset:
            title: translate:geolocation_mapset
            perm: admin[]
            icon: fa fa-map
            subPath: pages/yform.php
        layer:
            title: translate:geolocation_layer
            perm: admin[]
            icon: fa fa-cloud-download
            subPath: pages/yform.php
        docs:
            title: translate:geolocation_manpage
            perm: admin[]
            icon: fa fa-book
            subPath: help.php
        clear_cache:
            title: 'translate:geolocation_clear_cache'
            perm: admin[]
            itemclass: 'pull-right'
            linkclass: 'btn btn-delete'
            href:
                page: geolocation/config
                func: clear_cache

yform:
    geolocation/mapset:
        table_name: rex_geolocation_mapset
    geolocation/layer:
        table_name: rex_geolocation_layer

requires:
    php:
        version: '>=7.1'
    redaxo: '^5.11.0'
    packages:
        cronjob: '^2.7'
        yform: '^3.4'
